### PR TITLE
Database Performance Audit

### PR DESCRIPTION
**Pull request by Tobby8629**
proceed to check the database performance through the following steps:
- create a new column in the owners table (email column)
- populated the owners and visit table with data to reduce database performance 
- check the database performance and time of execution using EXPLAIN ANALYZE.
- use indexing to optimize slow queries in the database and improve execution time

Here is the result of the queries before INDEXING
time of execution query

Here is the results of the queries after INDEXING

answer 1

answer 2

### CODE REVIEW

**Review by bobb-Rob — COMMENTED** [review]
Hi @Tobby8629, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that your pair programming partners have not made their contribution to the project. The commit history currently shows that only one person did this project. Please your partner has pushed some code.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Thoth1111** [comment]
Hello reviewer, I've committed the parts I worked on.

**Review by omarsalem7 — APPROVED** [review]
Hi @Tobby8629, @Thoth1111 😊, 
# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ The performance improved after adding indexes
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Tobby8629** [comment]
Thank you very much for the review

**Pull request merged**
